<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>{0} Reference Manual</title>
  <meta name="author" content="{1}" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" href="style.css" media="all" title="default" />
  <link rel="stylesheet" href="print.css" media="print" />
</head>
<body>
<h1>{0} Reference Manual</h1>
<h2>{2}</h2>
<h2>Generated by {3}</h2>
<h3>{4}</h3>
<hr />
<h2>Table of Contents</h2>
<hr />
<h2>Module documentation</h2>
<hr />
<h2>File listings</h2>
<hr />
<h2>Dependency diagram</h2>