<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>{1}</title>
  <meta name="author" content="TODO" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" href="{0}" media="all" title="default" />
</head>
<body>
<h1>{1}</h1>
{2}
<hr />
<p>Generated by {3}</p>
</body>
</html>
