\documentclass[{0}]{{book}
\usepackage{{a4wide}
\usepackage{{makeidx}
\usepackage{{fancyhdr}
\usepackage{{graphicx}
\usepackage{{multicol}
\usepackage{{float}
\usepackage{{textcomp}
\usepackage{{alltt}
\usepackage[utf8]{{inputenc}
\usepackage{{listings}
\lstnewenvironment{{dcode}
{{ \lstset{{language=d} }
{{}
\lstset{{
  {5} literate=
  {5}          {{<=}{{{{$\leq$}}1
  {5}          {{>=}{{{{$\geq$}}1
  {5}          {{!=}{{{{$\neq$}}1
  {5}          {{...}{{{{$\dots$}}1
  {5}          {{~}{{{{$\sim$}}1,
  stringstyle=\ttfamily,
  inputencoding=utf8,
  extendedchars=false,
  columns=fixed,
  basicstyle=\small
}
\makeindex
\setcounter{{tocdepth}{{1}
\newcommand{{\clearemptydoublepage}{{\newpage{{\pagestyle{{empty}\cleardoublepage}}
\def\thechapter{{\Roman{{chapter}}
\def\thesection{{\arabic{{chapter}.\arabic{{section}}
% \renewcommand{{\footrulewidth}{{0.4pt}

\begin{{document}

\begin{{titlepage}
\vspace*{{7cm}
\begin{{center}
{{\Large {1} Reference Manual\\[1ex]\large {2} }\\
\vspace*{{1cm}
{{\large Generated by {3} }\\
\vspace*{{0.5cm}
{{\small {4} }\\
\end{{center}
\end{{titlepage}

\clearemptydoublepage
