#!/bin/sh

PHOBOS_SRC=$1
# Find source files, ignore phobos.d, cast.d, invariant.d, switch.d, unittest.d and the folder internal/.
FILES=`find $PHOBOS_SRC \( \! \( -name "phobos.d" -o -name "cast.d" -o -name "invariant.d" -o -name "switch.d" -o -name "unittest.d" \) -a \( -iname '*.d' -o -iname '*.di' \) \) -type f -print | sed -e "s@^$PHOBOS_SRC/*internal.\+@@"`

# Modify std.ddoc and write it out to data/phobos.ddoc.
python -c '
# import the module for regular expressions.
import re
# Open ddoc file to be modified.
ddoc = open("'$PHOBOS_SRC/std.ddoc'").read()
# Make "../" to "./".
ddoc = re.sub(r"\.\./(style.css|dmlogo.gif)", r"./\1", ddoc)
# Make some relative paths to absolute ones.
ddoc = re.sub(r"\.\./", "http://www.digitalmars.com/d/1.0/", ddoc)
# Replace with a DDoc macro.
ddoc = re.sub("Page generated by.+", "$(GENERATED_BY)", ddoc)
# Make e.g. "std_string.html" to "std.string.html".
ddoc = re.sub("href=\"std.+?\"", lambda m: m.group(0).replace("_", "."), ddoc)
# Linkify the title.
ddoc = re.sub("<h1>\$\(TITLE\)</h1>", "<h1><a href=\"$(SRCFILE)\">$(TITLE)</a></h1>", ddoc)
# Write new ddoc file.
open("data/phobos.ddoc", "w").write(ddoc)'

# Destination of all documentation files.
DOC="phobosdoc"
# Create the destination folders.
mkdir -p $DOC/htmlsrc

# Some files needed from dmd's doc folder.
PHOBOS_HTML=$PHOBOS_SRC/../../html/d/phobos
cp $PHOBOS_HTML/erfc.gif $PHOBOS_HTML/erf.gif $PHOBOS_HTML/../style.css $PHOBOS_HTML/../dmlogo.gif $DOC/
# Syntax highlighted files need html.css.
cp data/html.css $DOC/htmlsrc

# Generate documenation files.
dil ddoc $DOC/ -i -v data/phobos.ddoc data/phobos_overrides.ddoc -version=DDoc $FILES

# Generate syntax highlighted files.
HTMLSRC="$DOC/htmlsrc"
for DFILE in $FILES; do
  # Use sed to remove part of the path, convert '/' to '.' and remove the extension.
  HTMLFILE=`echo $DFILE | sed -e "s@^$PHOBOS_SRC/*@@" -e 's@/@.@g' -e 's@\.d$@@'`.html
  echo "FILE: $DFILE > $HTMLSRC/$HTMLFILE";
  dil hl --lines --syntax --html $DFILE > "$HTMLSRC/$HTMLFILE";
done
